# Node.js

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '21.x'
  displayName: 'Install Node.js'

- script: |
    cd frontend  
    npm install
    npm run build
  displayName: 'npm install and build'